version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.25.5
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Make build"
          command: "make build"

workflows:
  build-workflow:
    jobs:
      - build
